version: 2

models:
  - name: gold_beers_enriched
    description: "Enriched beer data with review statistics, popularity scores, brewery information, and full country names"
    columns:
      - name: id
        description: "Unique beer identifier"
        tests:
          - unique
          - not_null
      
      - name: name
        description: "Beer name"
        tests:
          - not_null
      
      - name: brewery_id
        description: "Reference to brewery"
        tests:
          - not_null
          - relationships:
              to: ref('silver_breweries')
              field: id
      
      - name: brewery_name
        description: "Name of the brewery"
      
      - name: country_code
        description: "ISO 2-letter country code"
      
      - name: country_name
        description: "Full country name from lookup table"
      
      - name: review_count
        description: "Total number of reviews for this beer"
        tests:
          - not_null
      
      - name: avg_rating
        description: "Average rating score across all reviews"
      
      - name: style_avg_rating
        description: "Average rating for all beers in this style (peer group average)"
      
      - name: beers_in_style
        description: "Total number of beers in this style category"
      
      - name: rating_vs_style_avg
        description: "Difference between this beer's rating and its style average (positive = above average)"
      
      - name: rating_tier_vs_style
        description: "Categorical rating tier compared to style peers"
        tests:
          - accepted_values:
              values: ['Well Above Average', 'Above Average', 'Average', 'Below Average', 'Well Below Average']
              config:
                severity: warn
      
      - name: popularity_score
        description: "Popularity score from 1-10 based on review count percentiles"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 10
              inclusive: true
      
      - name: is_highly_reviewed
        description: "Flag indicating beer has 100+ reviews"
        tests:
          - not_null
      
      - name: is_highly_rated
        description: "Flag indicating beer has average rating >= 4.0"
        tests:
          - not_null
      
      - name: has_consistent_ratings
        description: "Flag indicating low rating variance (stddev < 0.5)"
        tests:
          - not_null